fomp: fomp.f90
	ifort -O -qopenmp -o fomp fomp.f90 -g -traceback -CB
fomp2: fomp2.f90
	ifort -O -qopenmp -o fomp2 fomp2.f90 -g -traceback -CB
fomp3: fomp3.f90
	ifort -O -qopenmp -o fomp3 fomp3.f90 -g -traceback -CB
comp3: comp3.c
	icc -O -qopenmp -o comp3 comp3.c -g

